apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: xkeg49f9g-java-springboot 
  janus-idp.io/tekton: xkeg49f9g-java-springboot
  backstage.io/kubernetes-id: xkeg49f9g-java-springboot
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: xkeg49f9g-java-springboot
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml